import type { Meta, StoryObj } from "@storybook/react";
import { userEvent, within, waitFor, expect, fn } from "@storybook/test";
import {
  type UnknownOperation,
  type WithNovaEnvironment,
  getNovaDecorator,
  MockPayloadGenerator,
  getNovaEnvironmentForStory,
  EventingInterceptor,
} from "@nova/react-test-utils/apollo";
import { getSchema } from "../../testing-utils/getSchema";
import type { TypeMap } from "../../__generated__/schema.all.interface";
import { FeedbackContainer } from "./FeedbackContainer";
import { cacheConfig } from "../../testing-utils/apolloCacheConfig";
import type { events, FeedbackTelemetryEvent } from "../../events/events";
import * as React from "react";

const schema = getSchema();

const telemetryEventMock =
  fn<[{ event: FeedbackTelemetryEvent; source: unknown }]>();

type NovaParams = WithNovaEnvironment<UnknownOperation, TypeMap>;

const meta = {
  component: FeedbackContainer,
  decorators: [getNovaDecorator(schema, { cache: cacheConfig })],
  parameters: {
    novaEnvironment: {
      resolvers: {
        Feedback: () => ({
          id: "feedback:42",
        }),
        Node: ({ args }) => {
          console.log("args", args);
          const { id } = args as { id: string };

          if (id.startsWith("feedback:")) {
            return {
              __typename: "Feedback",
              id,
            };
          }
          return undefined;
        },
      },
    },
  } satisfies NovaParams,
  render: () => (
    <EventingInterceptor<typeof events>
      eventMap={{
        feedbackTelemetry: telemetryEventMock,
      }}
    >
      <FeedbackContainer />
    </EventingInterceptor>
  ),
} satisfies Meta<typeof FeedbackContainer>;

export default meta;
type Story = StoryObj<typeof meta>;

export const AutoGeneratedDataOnly: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = await canvas.findByRole("button", { name: "Like" });
    await expect(button).toBeInTheDocument();
  },
};

export const Primary: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: {
        Feedback: () => sampleFeedback,
      },
    },
  } satisfies NovaParams,
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = await canvas.findByRole("button", { name: "Like" });
    await expect(button).toBeInTheDocument();
  },
};

export const Liked: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: {
        Feedback: () => ({
          ...sampleFeedback,
          doesViewerLike: true,
        }),
      },
    },
  } satisfies NovaParams,
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = await canvas.findByRole("button", { name: "Unlike" });
    await expect(button).toBeInTheDocument();
  },
};

export const Like: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: {
        Feedback: () => sampleFeedback,
        FeedbackLikeMutationResult: () => ({
          feedback: {
            ...sampleFeedback,
            doesViewerLike: true,
          },
        }),
      },
    },
  } satisfies NovaParams,
  play: async ({ canvasElement }) => {
    const container = within(canvasElement);
    const likeButton = await container.findByRole("button", { name: "Like" });
    userEvent.click(likeButton);

    await container.findByRole("button", { name: "Unlike" });

    expect(telemetryEventMock).toHaveBeenCalledTimes(2);
    const call = telemetryEventMock.mock.calls[1];
    expect(call[0].event.data().operation).toBe("FeedbackLiked");
  },
};

export const LikeFailure: Story = {
  parameters: {
    novaEnvironment: {
      enableQueuedMockResolvers: false,
    },
  } satisfies NovaParams,
  play: async (context) => {
    const {
      graphql: { mock },
    } = getNovaEnvironmentForStory(context);

    await waitFor(async () => {
      const operation = mock.getMostRecentOperation();
      await expect(operation).toBeDefined();
    });
    await mock.resolveMostRecentOperation((operation) =>
      MockPayloadGenerator.generate(operation, {
        Feedback: () => sampleFeedback,
      }),
    );
    await Like.play?.(context);
    await waitFor(async () => {
      const operation = mock.getMostRecentOperation();
      expect(operation).toBeDefined();
    });
    mock.rejectMostRecentOperation(new Error("Like failed"));
    const container = within(context.canvasElement);
    await container.findByText("Something went wrong");
  },
};

export const QueryFailure: Story = {
  parameters: {
    novaEnvironment: {
      enableQueuedMockResolvers: false,
    },
  } satisfies NovaParams,
  play: async (context) => {
    const {
      graphql: { mock },
    } = getNovaEnvironmentForStory(context);
    await waitFor(async () => {
      const operation = mock.getMostRecentOperation();
      await expect(operation).toBeDefined();
    });
    await mock.rejectMostRecentOperation(new Error("Query failed"));
  },
};

export const Loading: Story = {
  parameters: {
    novaEnvironment: {
      enableQueuedMockResolvers: false,
    },
  } satisfies NovaParams,
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const loadingElement = await canvas.findByText("Loading...");
    await expect(loadingElement).toBeInTheDocument();
  },
};

const sampleFeedback = {
  id: "feedback:42",
  message: {
    text: "Feedback title",
  },
  doesViewerLike: false,
};
