import { graphql } from "@nova/react";
import {
  getNovaDecorator,
  getNovaEnvironmentForStory,
  MockPayloadGenerator as PayloadGenerator,
  type WithoutFragmentRefs,
  type WithNovaEnvironment,
  EventingProvider,
} from "@nova/react-test-utils/relay";
import type { Meta, StoryObj } from "@storybook/react";
import { userEvent, waitFor, within, expect } from "@storybook/test";
import type { TypeMap } from "../../__generated__/schema.all.interface";
import { FeedbackComponent } from "./Feedback";
import type { FeedbackStoryQuery } from "./__generated__/FeedbackStoryQuery.graphql";
import { getSchema } from "../../testing-utils/getSchema";
import * as React from "react";
import type { events } from "../../events/events";

const schema = getSchema();

const MockPayloadGenerator = new PayloadGenerator(schema);

const meta = {
  component: FeedbackComponent,
  decorators: [getNovaDecorator(schema)],
  parameters: {
    novaEnvironment: {
      query: graphql`
        query FeedbackStoryQuery($id: ID!) @relay_test_operation {
          feedback(id: $id) {
            ...Feedback_feedbackFragment
          }
        }
      `,
      variables: { id: "42" },
      referenceEntries: {
        feedback: (data) => data?.feedback,
      },
    },
  } satisfies WithNovaEnvironment<FeedbackStoryQuery, TypeMap>,
} satisfies Meta<typeof FeedbackComponent>;

export default meta;
type Story = StoryObj<WithoutFragmentRefs<typeof meta>>;

export const AutoGeneratedDataOnly: Story = {};

export const Primary: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: {
        Feedback: () => sampleFeedback,
      },
    },
  } satisfies WithNovaEnvironment<FeedbackStoryQuery, TypeMap>,
};

export const Liked: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: {
        Feedback: () => ({
          ...sampleFeedback,
          doesViewerLike: true,
        }),
      },
    },
  } satisfies WithNovaEnvironment<FeedbackStoryQuery, TypeMap>,
};

const likeResolvers = {
  Feedback: () => sampleFeedback,
  FeedbackLikeMutationResult: () => ({
    feedback: {
      ...sampleFeedback,
      doesViewerLike: true,
    },
  }),
};

export const Like: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: likeResolvers,
    },
  } satisfies WithNovaEnvironment<FeedbackStoryQuery, TypeMap>,
  play: async (context) => {
    const container = within(context.canvasElement);
    const likeButton = await container.findByRole("button", { name: "Like" });
    await userEvent.click(likeButton);

    const {
      graphql: { mock },
    } = getNovaEnvironmentForStory(context);

    await waitFor(async () => {
      const operation = mock.getMostRecentOperation();
      await expect(operation).toBeDefined();
    });
    await mock.resolveMostRecentOperation((operation) => {
      return MockPayloadGenerator.generate(operation, likeResolvers);
    });
  },
};

export const ArtificialFailureToShowcaseDecoratorBehaviorInCaseOfADevCausedError: Story =
  {
    parameters: {
      novaEnvironment: {
        enableQueuedMockResolvers: false,
      },
    } satisfies WithNovaEnvironment<FeedbackStoryQuery, TypeMap>,
    play: async (context) => {
      const {
        graphql: { mock },
      } = getNovaEnvironmentForStory(context);
      await waitFor(async () => {
        const operation = mock.getMostRecentOperation();
        await expect(operation).toBeDefined();
      });
      await mock.rejectMostRecentOperation(new Error("Query failed"));
    },
  };

const FeedbackWithDeleteDialog = (props: Story["args"]) => {
  const [open, setOpen] = React.useState(false);
  const [text, setText] = React.useState("");
  return (
    <EventingProvider<typeof events>
      eventMap={{
        onDeleteFeedback: (eventWrapper) => {
          setOpen(true);
          setText(eventWrapper.event.data().feedbackText);
          return Promise.resolve();
        },
      }}
    >
      {/* eslint-disable-next-line @typescript-eslint/ban-ts-comment */}
      {/* @ts-ignore we know feedback is passed through decorator */}
      <FeedbackComponent {...props} />
      <dialog open={open}>
        <button onClick={() => setOpen(false)}>Cancel</button>
        Are you sure you want to delete feedback "{text}"
      </dialog>
    </EventingProvider>
  );
};

export const WithDeleteDialog: Story = {
  ...Primary,
  render: (args) => <FeedbackWithDeleteDialog {...args} />,
  play: async (context) => {
    const container = within(context.canvasElement);
    const deleteButton = await container.findByRole("button", {
      name: "Delete feedback",
    });
    await userEvent.click(deleteButton);
    const dialog = await container.findByRole("dialog");
    await expect(dialog).toBeInTheDocument();
  },
};

const sampleFeedback = {
  id: "42",
  message: {
    text: "Feedback title",
  },
  doesViewerLike: false,
};
