import type { Meta, StoryObj } from "@storybook/react";
import { userEvent, within, waitFor, expect } from "@storybook/test";
import {
  type UnknownOperation,
  type WithNovaEnvironment,
  getNovaDecorator,
  getNovaEnvironmentForStory,
  getOperationName,
  getOperationType,
  MockPayloadGenerator as PayloadGenerator,
} from "@nova/react-test-utils/relay";
import type { TypeMap } from "../../__generated__/schema.all.interface";
import { FeedbackContainer } from "./FeedbackContainer";
import { schema } from "../../testing-utils/schema";

type NovaParameters = WithNovaEnvironment<UnknownOperation, TypeMap>;

const MockPayloadGenerator = new PayloadGenerator(schema);

const meta: Meta<typeof FeedbackContainer> = {
  component: FeedbackContainer,
  decorators: [getNovaDecorator(schema)],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const AutoGeneratedDataOnly: Story = {};

export const Primary: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: {
        Feedback: () => sampleFeedback,
      },
    },
  } satisfies NovaParameters,
};

export const Liked: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: {
        Feedback: () => ({
          ...sampleFeedback,
          doesViewerLike: true,
        }),
      },
    },
  } satisfies NovaParameters,
};

const likeResolvers = {
  Feedback: () => sampleFeedback,
  FeedbackLikeMutationResult: () => ({
    feedback: {
      ...sampleFeedback,
      doesViewerLike: true,
    },
  }),
};

export const Like: Story = {
  parameters: {
    novaEnvironment: {
      resolvers: likeResolvers,
    },
  } satisfies NovaParameters,
  play: async (context) => {
    const container = within(context.canvasElement);
    const likeButton = await container.findByRole("button", { name: "Like" });
    userEvent.click(likeButton);
    const {
      graphql: { mock },
    } = getNovaEnvironmentForStory(context);

    await waitFor(async () => {
      const operation = mock.getMostRecentOperation();
      await expect(operation).toBeDefined();
    });
    await mock.resolveMostRecentOperation((operation) => {
      return MockPayloadGenerator.generate(operation, likeResolvers);
    });
  },
};

export const LikeFailure: Story = {
  parameters: {
    novaEnvironment: {
      enableQueuedMockResolvers: false,
    },
  } satisfies NovaParameters,
  play: async (context) => {
    const container = within(context.canvasElement);
    const {
      graphql: { mock },
    } = getNovaEnvironmentForStory(context);

    await waitFor(async () => {
      const operation = mock.getMostRecentOperation();
      await expect(operation).toBeDefined();
    });
    const operation = mock.getMostRecentOperation();
    const operationName = getOperationName(operation);
    const operationType = getOperationType(operation);
    expect(operationName).toEqual("FeedbackContainerQuery");
    expect(operationType).toEqual("query");
    await mock.resolveMostRecentOperation((operation) => {
      return MockPayloadGenerator.generate(operation, {
        Feedback: () => sampleFeedback,
      });
    });
    const likeButton = await container.findByRole("button", { name: "Like" });
    userEvent.click(likeButton);
    await waitFor(async () => {
      const operation = mock.getMostRecentOperation();
      expect(operation).toBeDefined();
    });
    const nextOperation = mock.getMostRecentOperation();
    const nextOperationName = getOperationName(nextOperation);
    const nextOperationType = getOperationType(nextOperation);
    expect(nextOperationName).toEqual("FeedbackComponent_LikeMutation");
    expect(nextOperationType).toEqual("mutation");
    await mock.rejectMostRecentOperation(new Error("Like failed"));
    await container.findByText("Something went wrong");
  },
};

export const QueryFailure: Story = {
  parameters: {
    novaEnvironment: {
      enableQueuedMockResolvers: false,
    },
  } satisfies NovaParameters,
  play: async (context) => {
    const {
      graphql: { mock },
    } = getNovaEnvironmentForStory(context);
    await waitFor(async () => {
      const operation = mock.getMostRecentOperation();
      await expect(operation).toBeDefined();
    });
    await mock.rejectMostRecentOperation(new Error("Query failed"));
  },
};

export const Loading: Story = {
  parameters: {
    novaEnvironment: {
      enableQueuedMockResolvers: false,
    },
  } satisfies NovaParameters,
};

const sampleFeedback = {
  id: "42",
  message: {
    text: "Feedback title",
  },
  doesViewerLike: false,
};
