pr: none
trigger:
  - main

variables:
  - group: InfoSec-SecurityResults
  - name: tags
    value: production,externalfacing
  - name: serviceTreeID
    value: 6F8CD842-E117-412F-BAE4-56A3B6166594

jobs:
  - job: compliance
    displayName: Compliance checks
    pool:
      name: 1ES-Teams-Windows-2019-Compliant
    steps:
      - template: ./steps/service-tree.yml
        parameters:
          serviceTreeID: $(serviceTreeID)
      - template: ./steps/compliance-steps.yml

  - job: Release
    variables:
      - group: oss-secrets
    dependsOn: Compliance
    pool: "1ES-Teams-Ubuntu-Latest-Compliant"
    steps:
      - template: ./steps/service-tree.yml
        parameters:
          serviceTreeID: $(serviceTreeID)
      - script: yarn
        displayName: yarn
      - script: |
          yarn ci
        displayName: build and test [test]
      - script: |
          git config user.email "gql-svc@microsoft.com"
          git config user.name "Graphitation Service Account"
        displayName: Configure git for release
      - script: yarn release -y -n $(ossNpmToken) --access public
        displayName: Release
        env:
          NPM_AUTHTOKEN: $(ossGithubPAT)
