name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.repo_pat }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn ci
      - run: |
          git config user.email "gql-svc@microsoft.com"
          git config user.name "Nova Service Account"
      - run: yarn types
      - run: yarn release -y -n $NPM_AUTHTOKEN --access public
        env:
          NPM_AUTHTOKEN: ${{ secrets.npm_authtoken }}
